---
# file: tasks/validation.yml
#
# validation tasks.
#

- name: ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - pip_dir_source
    - pip_version
